-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Tempo de geração: 21-Set-2025 às 21:38
-- Versão do servidor: 8.0.30
-- versão do PHP: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `bunco_database`
--
CREATE DATABASE IF NOT EXISTS `bunco_database` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `bunco_database`;

-- --------------------------------------------------------

--
-- Estrutura da tabela `licoes`
--

CREATE TABLE `licoes` (
  `id` int NOT NULL,
  `titulo` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `conteudo` json NOT NULL,
  `tipo` enum('teoria','exercicio') COLLATE utf8mb4_general_ci NOT NULL,
  `modulo` int DEFAULT NULL,
  `ordem` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `licoes`
--

INSERT INTO `licoes` (`id`, `titulo`, `conteudo`, `tipo`, `modulo`, `ordem`, `created_at`) VALUES
(1, 'Algoritmos e lógica de programação', '[{\"tipo\": \"texto\", \"conteudo\": \"Para começar a nossa jornada, a gente precisa entender sobre algoritmos e lógica de programação.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Um algoritmo é uma sequência de passos para resolver um problema ou executar uma tarefa.\"}, {\"tipo\": \"exemplo\", \"passos\": [\"Esquente a água.\", \"Coloque o pó de café no filtro.\", \"Despeje a água quente no filtro.\", \"Aguarde o café coar.\", \"Sirva na xícara.\"], \"titulo\": \"Exemplo de algoritmo no dia a dia: Fazer um café\"}, {\"tipo\": \"texto\", \"conteudo\": \"Os algoritmos podem ser usados para resolver problemas simples, como trocar uma lâmpada, ou complexos, como navegar em um GPS.\"}, {\"tipo\": \"texto\", \"conteudo\": \"A programação também é um exemplo de algoritmo! Para fazer um bom código de programação, é preciso entender sobre algoritmo para fazer um código bom e funcional.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Lógica de programação é a capacidade de pensar e organizar passos de forma eficiente. Um algoritmo bem estruturado evita confusão e melhora a solução de problemas!\"}]', 'teoria', 1, 1, '2025-08-26 23:51:51'),
(2, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é sua vez! Responda as perguntas para praticar o que aprendeu.\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Um conjunto de imagens.\", \"Uma sequência de passos organizados para resolver um problema.\", \"Um software de computador.\"], \"pergunta\": \"O que é um algoritmo?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"Um algoritmo sempre precisa ser seguido em uma ordem lógica.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"Um algoritmo é um conjunto de _______ organizados para atingir um objetivo.\", \"resposta_correta\": \"passos\"}, {\"tipo\": \"ordenacao\", \"itens\": [\"Despeje a água quente no filtro.\", \"Sirva na xícara.\", \"Esquente a água.\", \"Coloque o pó de café no filtro.\", \"Aguarde o café coar.\"], \"pergunta\": \"Arraste as etapas para organizar o algoritmo de fazer um café:\", \"ordem_correta\": [2, 3, 0, 4, 1]}, {\"dica\": \"Lembre-se de incluir todos os passos, desde pegar a escova até enxaguar a boca.\", \"tipo\": \"desafio\", \"pergunta\": \"Descreva um algoritmo para escovar os dentes, listando os passos corretamente.\"}]', 'exercicio', 1, 2, '2025-08-26 23:51:51'),
(3, 'Como escrever um algoritmo?', '[{\"tipo\": \"texto\", \"conteudo\": \"Para criar um algoritmo, siga três passos:\\nIdentificar o problema\\nListar os passos necessários\\nSeguir uma ordem lógica\"}, {\"tipo\": \"texto\", \"conteudo\": \"Exemplo: Algoritmo para atravessar a rua com segurança\\nParar na calçada.\\nOlhar para os dois lados.\\nEsperar os carros passarem.\\nAtravessar na faixa de pedestres.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Nesse exemplo, a lógica de programação foi aplicada:\\nDecisões: Se há carros vindo, não atravesse.\\nSequência: Os passos devem estar na ordem certa.\\nRepetição: Se ainda houver carros, continue esperando.\"}, {\"tipo\": \"texto\", \"conteudo\": \"A lógica de programação ensina a organizar o pensamento para criar soluções eficientes. Ela é essencial para escrever bons algoritmos!\"}]', 'teoria', 1, 3, '2025-08-26 23:51:51'),
(4, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora, vamos ver se você entendeu a aula anterior.\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Passos aleatórios.\", \"Ordem lógica e clareza.\", \"Muitas palavras difíceis.\"], \"pergunta\": \"O que um bom algoritmo deve ter?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"No algoritmo para atravessar a rua, devemos atravessar primeiro e depois olhar para os lados.\", \"resposta_correta\": false}, {\"tipo\": \"complete\", \"pergunta\": \"Se houver carros vindo, eu devo ________ antes de atravessar.\", \"resposta_correta\": \"esperar\"}, {\"tipo\": \"ordenacao\", \"itens\": [\"Olhar para os dois lados.\", \"Parar na calçada.\", \"Atravessar na faixa de pedestres.\", \"Esperar os carros passarem.\"], \"pergunta\": \"Arraste as etapas para organizar o algoritmo de atravessar a rua:\", \"ordem_correta\": [1, 0, 3, 2]}, {\"dica\": \"Lembre-se de incluir todos os passos, desde pegar os ingredientes até servir o sanduíche.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um algoritmo para preparar um sanduíche e organize os passos corretamente.\"}]', 'exercicio', 1, 4, '2025-08-26 23:51:52'),
(5, 'Fluxogramas e pseudocódigo', '[{\"tipo\": \"texto\", \"conteudo\": \"Existem dois jeitos de representar um algoritmo sem uma linguagem de programação, e nós vamos conhecer agora!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Fluxograma: Os passos do algoritmo são representados em desenho (imagem de um fluxograma)\\n\\nCada forma geométrica no fluxograma tem um significado específico para representar diferentes tipos de ações ou decisões.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Para entender todos os símbolos utilizados em fluxogramas, acesse este link no seu computador:\\n\\nhttps://www.lucidchart.com/pages/pt/fluxograma-simbologia\"}, {\"tipo\": \"texto\", \"conteudo\": \"Pseudocódigo: O algoritmo é escrito de forma estruturada, parecendo até mesmo um código de programação (imagem de um pseudocódigo)\\n\\nO pseudocódigo usa uma linguagem simples e próxima do português para descrever os passos do algoritmo.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Existem algumas ferramentas de pseudocódigo que funcionam como linguagens de programação educacionais, como o Visualg e o Portugol, mas neste curso vamos aprender a programar com Python.\"}]', 'teoria', 1, 5, '2025-08-26 23:51:52'),
(6, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Vamos praticar a criação de algoritmos com fluxogramas e pseudocódigos!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Uma linguagem de programação difícil.\", \"Um jeito simples de escrever algoritmos antes de programar.\", \"Um código usado só por especialistas.\"], \"pergunta\": \"O que é um pseudocódigo?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"Um fluxograma é representado apenas por números e símbolos matemáticos.\", \"resposta_correta\": false}, {\"tipo\": \"complete\", \"pergunta\": \"O pseudocódigo ajuda a planejar um algoritmo antes de ________.\", \"resposta_correta\": \"programar\"}, {\"tipo\": \"ordenacao\", \"itens\": [\"Beba a água.\", \"Abra a torneira.\", \"Pegue um copo.\", \"Encha o copo de água.\"], \"pergunta\": \"Arraste as etapas para organizar o pseudocódigo de tomar água:\", \"ordem_correta\": [2, 1, 3, 0]}, {\"dica\": \"Comece identificando os passos básicos da atividade e depois organize em sequência lógica.\", \"tipo\": \"desafio\", \"pergunta\": \"Escolha uma atividade simples, como amarrar um tênis.\\nEscreva um pseudocódigo para essa atividade.\\nSe quiser, desenhe um fluxograma para representar seu algoritmo.\"}]', 'exercicio', 1, 6, '2025-08-26 23:51:52'),
(7, 'Tipos de dados', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora podemos começar a entrar no mundo do Python! E vamos primeiro entender sobre os tipos de dados.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Os tipos de dados são as classificações das informações e variáveis que usamos no nosso código. No Python, os principais tipos são:\"}, {\"tipo\": \"texto\", \"conteudo\": \"Int: São os números inteiros (ex: 10, -3, 45)\\nnumero = -3\"}, {\"tipo\": \"texto\", \"conteudo\": \"Float: São os números decimais (ex: 3.14, 2.5, -4.1)\\nnumero = 2.14\"}, {\"tipo\": \"texto\", \"conteudo\": \"Str (ou String): São as palavras e textos (ex: \\\"Olá, Mundo\\\")\\ntexto = \\\"Olá\\\"\\n\\n*Obs: Os textos e palavras precisam estar entre aspas!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Bool (ou Boolean): Verdadeiro ou Falso (True, False)\\nvariavel = True\"}, {\"tipo\": \"texto\", \"conteudo\": \"Cada tipo de dado tem um propósito e precisa ser usado corretamente para evitar erros no código!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Diferente de outras linguagens de programação, no Python, não é preciso \\\"declarar\\\" o tipo de dado antes da variável.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Para descobrir o tipo da variável, podemos usar uma função chamada type()\\n\\nprint(type(10))     # int\\nprint(type(3.14))   # float\\nprint(type(\\\"Oi\\\"))   # str\\nprint(type(True))   # bool\"}]', 'teoria', 2, 1, '2025-08-26 23:51:52'),
(8, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é sua vez! Responda as perguntas para praticar.\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"3.5\", \"10\", \"\\\"Python\\\"\"], \"pergunta\": \"Qual desses é um número inteiro (int)?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O tipo bool pode armazenar números.\", \"resposta_correta\": false}, {\"tipo\": \"complete\", \"pergunta\": \"O tipo de dado que usamos para armazenar palavras e frases em Python é chamado de ________.\", \"resposta_correta\": \"string\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"int\", \"float\", \"str\"], \"pergunta\": \"Que tipo de dado será mostrado ao rodar o código ao lado: print(type(4.75))\", \"resposta_correta\": 1}, {\"dica\": \"Lembre-se: int são números inteiros, float são decimais, str são textos entre aspas e bool são True ou False.\", \"tipo\": \"desafio\", \"pergunta\": \"Escreva três exemplos de valores para cada tipo de dado: int, float, str e bool.\"}]', 'exercicio', 2, 2, '2025-08-26 23:51:52'),
(9, 'Conversão de dados', '[{\"tipo\": \"texto\", \"conteudo\": \"Em Python, podemos converter um tipo de dado para outro usando funções de conversão.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Principais funções de conversão:\\n int() → Converte para número inteiro\\n float() → Converte para número decimal\\n str() → Converte para texto\\n bool() → Converte para verdadeiro ou falso\"}, {\"tipo\": \"texto\", \"conteudo\": \"Alguns exemplos de conversão:\\nx = int(3.9)     # x será 3\\ny = float(10)    # y será 10.0\\nz = str(25)      # z será \\\"25\\\"\\nw = bool(0)      # w será False\"}, {\"tipo\": \"texto\", \"conteudo\": \"Mas atenção! Em alguns casos, não é possível converter dados! Por exemplo, tentar converter um texto para número irá causar um erro!\"}]', 'teoria', 2, 3, '2025-08-26 23:51:52'),
(14, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora, vamos testar sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"str()\", \"int()\", \"float()\"], \"pergunta\": \"Qual dessas funções converte um número decimal em inteiro?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"A conversão int(1.8) vai causar um erro.\", \"resposta_correta\": false}, {\"tipo\": \"complete\", \"pergunta\": \"A função float() converte um número inteiro para um número _______.\", \"resposta_correta\": \"decimal\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"7.8\", \"7\", \"8\"], \"pergunta\": \"O que acontece ao rodar este código?\\nprint(int(7.8))\", \"resposta_correta\": 1}, {\"dica\": \"Use as funções de conversão int(), float(), str() e bool() em valores como 5, 3.14, \\\"10\\\", \\\"hello\\\", True e False para ver os resultados.\", \"tipo\": \"desafio\", \"pergunta\": \"Faça você mesmo conversões de valores e descubra o que acontece!\"}]', 'exercicio', 2, 4, '2025-08-26 23:51:52'),
(15, 'Desafio', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é hora do desafio! Resolva os exercícios no seu computador.\"}, {\"dica\": \"Use a função type() dentro do print() para mostrar o tipo de cada variável.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 1: Crie três variáveis:\\n- Uma para armazenar um número inteiro.\\n- Uma para armazenar um número decimal.\\n- Uma para armazenar um texto.\\\\n\\\\nDepois, use print() para exibir os valores e seus respectivos tipos de dados.\"}, {\"dica\": \"Atribua um número inteiro a uma variável, por exemplo: idade = 25\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 2: Crie um código que armazene uma variável inteira.\"}, {\"dica\": \"Use dois comandos print() ou um único print() separando os números com vírgula.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 3: Escreva um código que exiba dois números.\"}, {\"dica\": \"Use uma variável para armazenar True ou False, depois use print() para exibir.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 4: Crie um código que armazene um valor booleano (True ou False) e exiba esse valor na tela.\"}, {\"dica\": \"Use a função int() para converter um número decimal como 7.8 para inteiro.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 5: Crie um código que converta um número decimal para um número inteiro antes de exibi-lo na tela.\"}]', 'exercicio', 2, 5, '2025-08-26 23:51:52'),
(16, 'Exibindo mensagens com print()', '[{\"tipo\": \"texto\", \"conteudo\": \"Nessa parte, vamos entender mais a função print(). Vamos nessa!\"}, {\"tipo\": \"texto\", \"conteudo\": \"A função print() serve para mostrar mensagens na tela.\"}, {\"tipo\": \"texto\", \"conteudo\": \"print(\\\"Olá, mundo!\\\") o que está dentro do parênteses será exibido na tela\"}, {\"tipo\": \"texto\", \"conteudo\": \"O print() pode mostrar diversos tipos de dados \\nprint(10)         # Número inteiro  \\nprint(3.14)       # Número decimal  \\nprint(True)       # Valor booleano  \\nprint(\\\"Python\\\")   # Texto (string)\"}, {\"tipo\": \"texto\", \"conteudo\": \"Podemos exibir vários valores ao mesmo tempo, separados por vírgula:\\nprint(\\\"O resultado é:\\\", 10 + 5)\"}]', 'teoria', 3, 1, '2025-08-26 23:51:52'),
(17, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é a sua vez! Responda as perguntas para praticar\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"echo(\\\"Aprendendo Python!\\\")\", \"print(\\\"Aprendendo Python!\\\")\", \"console.log(\\\"Aprendendo Python!\\\")\"], \"pergunta\": \"Qual comando exibe a mensagem \\\"Aprendendo Python!\\\" na tela?\", \"resposta_correta\": 1}, {\"tipo\": \"complete\", \"pergunta\": \"Como exibir a mensagem \\\"Olá, Mundo!\\\" na tela?\", \"resposta_correta\": \"print(\\\"Olá, Mundo!\\\")\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Soma: 5 + 3\", \"Soma: 8\", \"8\"], \"pergunta\": \"O que será exibido ao rodar este código?\\nprint(\\\"Soma:\\\", 5 + 3)\", \"resposta_correta\": 1}, {\"dica\": \"Use print(\\\"Meu nome é\\\", nome, \\\"e tenho\\\", idade, \\\"anos\\\") substituindo nome e idade pelos seus valores\", \"tipo\": \"desafio\", \"pergunta\": \"Escreva um código Python que exiba seu nome e idade na tela usando print()\"}]', 'exercicio', 3, 2, '2025-08-26 23:51:52'),
(18, 'Recebendo informações com input()', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender a usar a função input()\"}, {\"tipo\": \"texto\", \"conteudo\": \"A função input() permite que o usuário digite informações.\"}, {\"tipo\": \"texto\", \"conteudo\": \"nome = input(\\\"Qual é o seu nome? \\\")\\nprint(\\\"Olá,\\\", nome)\\nO que o usuário digitar será armazenado na variável.\"}, {\"tipo\": \"texto\", \"conteudo\": \"IMPORTANTE! O input() sempre retorna um texto (string) mesmo se o usuário digitar números.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Para o usuário poder digitar um número do tipo int ou float, é preciso fazer a conversão: \\nidade = int(input(\\\"Digite sua idade: \\\"))\"}]', 'teoria', 3, 3, '2025-08-26 23:51:52'),
(19, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Vamos testar o seu raciocínio!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"print()\", \"input()\", \"scan()\"], \"pergunta\": \"Qual função recebe dados digitados pelo usuário?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O comando idade = input(\\\"Digite sua idade: \\\") guarda a idade como um número inteiro.\", \"resposta_correta\": false}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Bem-vindo, nome\", \"Bem-vindo, Ana\", \"Digite seu nome: Ana\"], \"pergunta\": \"O que será exibido se o usuário digitar \\\"Ana\\\" no código abaixo?\\nnome = input(\\\"Digite seu nome: \\\")\\nprint(\\\"Bem-vindo,\\\", nome)\", \"resposta_correta\": 1}, {\"dica\": \"Use dois comandos input() e depois um print() combinando as duas variáveis.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um programa que peça ao usuário seu nome e sua comida favorita, depois exiba a mensagem:\\n\\\"Olá, [nome]! Eu também gosto de [comida]!\\\"\"}]', 'exercicio', 3, 4, '2025-08-26 23:51:52'),
(20, 'Melhorando a exibição', '[{\"tipo\": \"texto\", \"conteudo\": \"Podemos personalizar a exibição usando algumas técnicas!\"}, {\"tipo\": \"texto\", \"conteudo\": \"É possível juntar strings com +\\nnome = \\\"Lucas\\\"\\nprint(\\\"Olá, \\\" + nome + \\\"!\\\")\\nImportante: só funciona com strings!\"}, {\"tipo\": \"texto\", \"conteudo\": \"F-Strings: Existe a possibilidade de colocar as variáveis dentro das aspas, sem precisar de vírgula ou + \\nidade = 25\\nprint(f\\\"Você tem {idade} anos.\\\")\"}, {\"tipo\": \"texto\", \"conteudo\": \"Para quebrar a linha dentro do print(), use o comando \\\\n\\nprint(\\\"Linha 1\\\\nLinha 2\\\")  # \\\\n quebra a linha\"}, {\"tipo\": \"texto\", \"conteudo\": \"Para adicionar uma tabulação, use o comando \\\\t \\nprint(\\\"Nome:\\\\tAna\\\")        # \\\\t adiciona um tab\"}]', 'teoria', 3, 5, '2025-08-26 23:51:52'),
(21, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é a hora de testar o seu conhecimento!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"print(f\\\"Olá {nome}\\\")\", \"print(f(\\\"Olá {nome}\\\"))\", \"print(f\'Olá\' nome)\"], \"pergunta\": \"Qual dessas opções usa f-strings corretamente?\", \"resposta_correta\": 0}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O comando print(\\\"Meu nome é\\\", nome) funciona sem erro.\", \"resposta_correta\": true}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Laranja Banana\", \"Laranja\\\\nBanana\", \"Laranja\\nBanana\"], \"pergunta\": \"O que será impresso?\\nprint(\\\"Laranja\\\\nBanana\\\")\", \"resposta_correta\": 2}, {\"dica\": \"Use input() para receber os dados e f-strings para formatar a mensagem final.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um programa que peça o nome e a cidade do usuário e exiba a mensagem:\\nOlá, [nome]! Como está o tempo em [cidade] hoje?\"}]', 'exercicio', 3, 6, '2025-08-26 23:51:52'),
(22, 'Desafio', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é hora do desafio! Resolva os exercícios no seu computador.\"}, {\"dica\": \"Use input() para receber o nome e print() para exibir a mensagem de boas-vindas.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 1: Crie um programa que peça o nome do usuário e exiba uma mensagem de boas-vindas com esse nome.\"}, {\"dica\": \"Use dois comandos input() e depois um print() mostrando os dois números.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 2: Peça ao usuário para digitar dois números e exiba eles em sequência.\"}, {\"dica\": \"Use f-strings para formatar a mensagem: print(f\\\"Olá, {nome}! Você tem {idade} anos.\\\")\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 3: Crie um programa que peça ao usuário seu nome e idade e exiba uma mensagem formatada como:\\n\\\"Olá, [nome]! Você tem [idade] anos.\\\"\"}, {\"dica\": \"Use três variáveis diferentes para dia, mês e ano, depois combine em uma f-string.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 4: Peça ao usuário para digitar seu dia, mês e ano de nascimento e exiba a seguinte mensagem:\\n\\\"Você nasceu no dia [dia] do mês [mês] do ano [ano]!\\\"\"}, {\"dica\": \"Peça primeiro a saudação e depois o nome, então use: print(f\\\"{saudacao}, {nome}!\\\")\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 5: Crie um código que peça ao usuário seu nome e uma saudação (exemplo: \\\"Bom dia\\\") e exiba a mensagem no formato:\\n\\\"Bom dia, [nome]!\\\"\"}]', 'exercicio', 3, 7, '2025-08-26 23:51:52'),
(23, 'Operadores aritméticos', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender sobre operadores aritméticos!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Os operadores aritméticos são usados para fazer cálculos matemáticos. Alguns deles são:\"}, {\"tipo\": \"texto\", \"conteudo\": \"Soma (+), Subtração (-), Multiplicação (*), Divisão (/)\"}, {\"tipo\": \"texto\", \"conteudo\": \"Divisão inteira (//): É o resultado da divisão com o resto, sem ir para a parte decimal. Por exemplo, 5 // 3 seria igual a 1.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Resto da divisão (%): É o resto da divisão entre dois números. Por exemplo, 5 % 3 seria igual a 2.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Exponenciação (**): É basicamente elevar um número a outro. Por exemplo, 2 ** 3 vai resultar em 8.\"}, {\"tipo\": \"texto\", \"conteudo\": \"a = 10\\nb = 3\\nprint(a + b)  # Soma\\nprint(a - b)  # Subtração\\nprint(a * b)  # Multiplicação\\nprint(a / b)  # Divisão normal\\nprint(a // b) # Divisão inteira\\nprint(a % b)  # Resto da divisão\\nprint(a ** b) # Exponenciação\"}, {\"tipo\": \"texto\", \"conteudo\": \"Assim como na matemática, existe uma ordem para resolver as operações:\\nParênteses ()\\nExponenciação **\\nMultiplicação *, Divisão /, Divisão inteira // e Módulo %\\nSoma + e Subtração -\\nCritério de desempate: Da esquerda para a direita.\"}]', 'teoria', 4, 1, '2025-08-26 23:51:52'),
(24, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é sua vez! Resolva os exercícios para praticar.\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"^\", \"**\", \"//\"], \"pergunta\": \"Qual operador usamos para calcular a potência de um número?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O operador % retorna o resto da divisão entre dois números.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"print(\\\"Soma:\\\", 3 ____ 4)\", \"resposta_correta\": \"+\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"20\", \"14\", \"24\"], \"pergunta\": \"O que será impresso?\\nprint(2 + 3 * 4)\", \"resposta_correta\": 1}, {\"dica\": \"Use input() para receber os números (lembre-se de converter para int ou float) e depois calcule e exiba as quatro operações.\", \"tipo\": \"desafio\", \"pergunta\": \"Escreva um código que peça dois números ao usuário e exiba:\\nA soma\\nA subtração\\nO produto\\nO quociente (divisão)\"}]', 'exercicio', 4, 2, '2025-08-26 23:51:52'),
(25, 'Operadores relacionais', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender sobre operadores relacionais!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Os operadores relacionais são usados para comparar valores.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Os operadores relacionais são:\\nIgual a: ==\\nDiferente de: !=\\nMaior que: >\\nMenor que: <\\nMaior ou igual a: >=\\nMenor ou igual a: <=\"}, {\"tipo\": \"texto\", \"conteudo\": \"a = 10\\nb = 5\\nprint(a > b)   # True (10 é maior que 5)\\nprint(a < b)   # False (10 não é menor que 5)\\nprint(a == b)  # False (10 não é igual a 5)\\nprint(a != b)  # True (10 é diferente de 5)\"}, {\"tipo\": \"texto\", \"conteudo\": \"Cuidado! Para comparar valores, usamos == e não apenas =\\na = 5   # Atribuição\\nprint(a == 5)  # Comparação (True)\"}]', 'teoria', 4, 3, '2025-08-26 23:51:52'),
(26, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos praticar as comparações!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"!=\", \"==\", \"<\"], \"pergunta\": \"Qual desses operadores significa \\\"diferente de\\\"?\", \"resposta_correta\": 0}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O operador > verifica se um número é menor que outro.\", \"resposta_correta\": false}, {\"tipo\": \"complete\", \"pergunta\": \"print(20 ___ 10) #True\", \"resposta_correta\": \">\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"True\", \"False\"], \"pergunta\": \"print(10 <= 20)\", \"resposta_correta\": 0}, {\"dica\": \"Use input() para receber os números, converta para int ou float, e use operadores de comparação como >= para verificar.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um código que peça dois números para o usuário e imprima True se for maior ou igual e False caso não seja.\"}]', 'exercicio', 4, 4, '2025-08-26 23:51:52'),
(27, 'Operadores lógicos', '[{\"tipo\": \"texto\", \"conteudo\": \"Vamos ver o último tipo de operadores: os operadores lógicos!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Os operadores lógicos são usados para combinar condições. Esses operadores são:\"}, {\"tipo\": \"texto\", \"conteudo\": \"And (E): \\\"cond1 and cond2\\\" Vai retornar True APENAS se as duas condições forem verdadeiras\\npode_dirigir = idade >= 18 and tem_carteira\"}, {\"tipo\": \"texto\", \"conteudo\": \"Or (Ou): \\\"cond1 or cond2\\\" Vai retornar True se pelo menos uma das duas condições for verdadeira\\ndescansar = chovendo or feriado\"}, {\"tipo\": \"texto\", \"conteudo\": \"Not (negação): \\\"not cond1\\\" Inverte o valor da condição. Por exemplo, se a condição for verdadeira, o not transforma em falsa e vice-versa\\ndescansar = not recuperacao\"}]', 'teoria', 4, 5, '2025-08-26 23:51:52'),
(28, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"and\", \"or\", \"not\"], \"pergunta\": \"Qual operador lógico retorna Verdadeiro (True) se ambas as condições forem verdadeiras?\", \"resposta_correta\": 0}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O operador not inverte um valor lógico.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"print(5 > 3 ___ 2 < 1) #True\", \"resposta_correta\": \"or\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"True\", \"False\"], \"pergunta\": \"print(True and False)\", \"resposta_correta\": 1}, {\"dica\": \"Use numero % 2 == 0 and numero % 3 == 0 para verificar se é divisível por ambos.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um código que veja se um número é divisível por 2 e por 3 e retorne algo para o usuário. (Dica: use o operador %).\"}]', 'exercicio', 4, 6, '2025-08-26 23:53:01'),
(29, 'Desafio', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é hora do desafio! Resolva os exercícios no seu computador.\"}, {\"dica\": \"Use input() para receber os números, converta para float, e depois calcule as quatro operações básicas.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 1: Peça ao usuário dois números e exiba a soma, subtração, multiplicação e divisão entre eles.\"}, {\"dica\": \"Use o operador ** para exponenciação: resultado = primeiro_numero ** segundo_numero\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 2: Crie um código que peça dois números ao usuário e exiba o resultado de um número elevado ao outro.\"}, {\"dica\": \"Dobro = número * 2, Triplo = número * 3. Use uma f-string para exibir os resultados.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 3: Peça ao usuário para digitar um número e exiba o dobro e o triplo desse número.\"}, {\"dica\": \"Use o operador // para divisão inteira: resultado = primeiro_numero // segundo_numero\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 4: Crie um código que peça dois números ao usuário e mostre o resultado da divisão inteira entre eles.\"}, {\"dica\": \"Use o operador > para comparar: print(primeiro_numero > segundo_numero)\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 5: Crie um código que peça dois números ao usuário e exiba se o primeiro é maior que o segundo.\"}]', 'exercicio', 4, 7, '2025-08-26 23:53:56'),
(30, 'If/Elif/Else', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender sobre estruturas condicionais!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Elas permitem que um programa tome decisões com base em condições. Um exemplo é o if/else\"}, {\"tipo\": \"texto\", \"conteudo\": \"O que é um if/else? O if verifica se uma condição é verdadeira. O else define o que acontece se a condição for falsa.\"}, {\"tipo\": \"texto\", \"conteudo\": \"idade = 18\\nif idade >= 18:\\n    print(\\\"Você é maior de idade.\\\")\\nelse:\\n    print(\\\"Você é menor de idade.\\\")\\n\\nSe a idade for maior ou igual a 18, o programa imprime \\\"Você é maior de idade\\\". Senão, imprime \\\"Você é menor de idade\\\".\"}, {\"tipo\": \"texto\", \"conteudo\": \"Também podemos adicionar o elif. O elif significa \\\"senão se\\\". Ele permite testar mais condições antes do else.\"}, {\"tipo\": \"texto\", \"conteudo\": \"nota = 7\\nif nota >= 7:\\n    print(\\\"Aprovado!\\\")\\nelif nota >= 5:\\n    print(\\\"Recuperação!\\\")\\nelse:\\n    print(\\\"Reprovado.\\\")\\n\\nelif significa \\\"senão se\\\". Ele permite testar mais condições antes do else.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Também é possível colocar um if sem colocar o else. Caso seja falso, o código segue normalmente: \\n\\nvalor = 2000\\nquantidade = 5\\nif quantidade > 5:\\n    desconto = 10/100       #10%\"}]', 'teoria', 5, 1, '2025-08-26 23:54:25'),
(31, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"O programa exibe um erro.\", \"O código dentro do if é ignorado e o programa continua.\", \"O Python escolhe outro bloco para executar.\"], \"pergunta\": \"O que acontece se a condição do if for falsa e não houver um else?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O elif permite testar várias condições antes de chegar no else.\", \"resposta_correta\": true}, {\"tipo\": \"ordenacao\", \"itens\": [\"print(\\\"Pode dirigir!\\\")\", \"if idade >= 18:\", \"idade = int(input(\\\"Digite sua idade: \\\"))\"], \"pergunta\": \"Ordene o código corretamente para verificar se uma pessoa pode dirigir.\", \"ordem_correta\": [2, 1, 0]}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Aprovado\", \"Recuperação\", \"Reprovado\"], \"pergunta\": \"nota = 6\\nif nota >= 7:\\n    print(\\\"Aprovado\\\")\\nelif nota >= 5:\\n    print(\\\"Recuperação\\\")\\nelse:\\n    print(\\\"Reprovado\\\")\", \"resposta_correta\": 1}, {\"dica\": \"Use if/else para verificar a condição do salário e calcule o novo salário com o aumento percentual.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um código que pergunte o salário de um funcionário e calcule um aumento:\\nSe o salário for menor que R$ 2000, o aumento é de 10%.\\nSenão, o aumento é de 5%.\"}]', 'exercicio', 5, 2, '2025-08-26 23:54:25'),
(32, 'Estrutura Match Case', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender sobre o match case!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Ele permite comparar valores de forma mais clara e organizada.\"}, {\"tipo\": \"texto\", \"conteudo\": \"O que é o match case? O match é como um \\\"interruptor\\\". Ele verifica várias opções e executa a que corresponder.\"}, {\"tipo\": \"texto\", \"conteudo\": \"comando = input(\\\"Digite um comando: \\\")\\n\\nmatch comando:\\n    case \\\"start\\\":\\n        print(\\\"Iniciando o programa...\\\")\\n    case \\\"stop\\\":\\n        print(\\\"Parando o programa...\\\")\\n    case _:\\n        print(\\\"Comando inválido!\\\")\\n\\nO case \\\"_\\\" funciona como o else, pegando qualquer valor não listado.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Aqui está um exemplo com múltiplos valores: \\ndia = input(\\\"Digite um dia da semana: \\\")\\nmatch dia:\\n    case \\\"sábado\\\" | \\\"domingo\\\":\\n        print(\\\"É fim de semana!\\\")\\n    case _:\\n        print(\\\"É um dia útil.\\\")\\n\\nSe o usuário digitar \\\"sábado\\\" ou \\\"domingo\\\", o programa reconhece como fim de semana.\"}]', 'teoria', 5, 3, '2025-08-26 23:54:25'),
(33, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Ele é executado quando nenhum dos outros case acontece.\", \"Ele compara apenas números.\", \"Ele encerra o programa.\"], \"pergunta\": \"Qual é a função do _ no match case?\", \"resposta_correta\": 0}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"No match case, podemos usar | para testar múltiplos valores no mesmo caso.\", \"resposta_correta\": true}, {\"tipo\": \"ordenacao\", \"itens\": [\"case \\\"vermelho\\\": print(\\\"Cor quente!\\\")\", \"match cor:\", \"cor = input(\\\"Digite uma cor: \\\")\", \"case _: print(\\\"Cor não reconhecida\\\")\"], \"pergunta\": \"Ordene o código corretamente para exibir mensagens com base na cor digitada pelo usuário.\", \"ordem_correta\": [3, 2, 1, 4]}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Pausando...\", \"Parando...\", \"Comando desconhecido\"], \"pergunta\": \"comando = \\\"play\\\"\\nmatch comando:\\n    case \\\"pause\\\":\\n        print(\\\"Pausando...\\\")\\n    case \\\"stop\\\":\\n        print(\\\"Parando...\\\")\\n    case _:\\n        print(\\\"Comando desconhecido\\\")\", \"resposta_correta\": 2}, {\"dica\": \"Use match case com múltiplos valores separados por | para cada estação do ano.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um programa que pergunte o nome de um mês e diga a estação correspondente:\\n\\\"junho\\\", \\\"julho\\\", \\\"agosto\\\" → Inverno\\n\\\"setembro\\\", \\\"outubro\\\", \\\"novembro\\\" → Primavera\\n\\\"dezembro\\\", \\\"janeiro\\\", \\\"fevereiro\\\" → Verão\\n\\\"março\\\", \\\"abril\\\", \\\"maio\\\" → Outono\"}]', 'exercicio', 5, 4, '2025-08-26 23:54:25'),
(34, 'Desafio', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é hora do desafio! Resolva os exercícios no seu computador.\"}, {\"dica\": \"Use if/elif/else para verificar três condições: > 0, < 0, e == 0.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 1: Peça ao usuário para digitar um número e exiba se ele é positivo, negativo ou zero.\"}, {\"dica\": \"Use if/else com a condição idade >= 18 para verificar maioridade.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 2: Crie um código que peça a idade do usuário e exiba se ele é maior ou menor de idade.\"}, {\"dica\": \"Use número % 2 == 0 para verificar se é par, else para ímpar.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 3: Peça ao usuário para digitar um número, verifique se ele é par ou ímpar e exiba uma mensagem personalizada.\"}, {\"dica\": \"Use if/elif/else ou match case para tratar cada letra do turno.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 4: Crie um programa que pergunte ao usuário em qual turno ele estuda (\\\"M\\\" para manhã, \\\"T\\\" para tarde e \\\"N\\\" para noite) e exiba uma mensagem personalizada para cada opção.\"}, {\"dica\": \"Use case com | para agrupar dias uteis (segunda a sexta) e fins de semana (sábado e domingo).\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 5: Use match case para criar um programa que peça ao usuário para digitar um dia da semana e exiba uma mensagem dizendo se é um dia útil ou final de semana.\"}]', 'exercicio', 5, 5, '2025-08-26 23:54:25'),
(35, 'Introdução ao While', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender sobre o loop while!\"}, {\"tipo\": \"texto\", \"conteudo\": \"O while é uma estrutura que permite repetir blocos de código enquanto uma condição for verdadeira.\"}, {\"tipo\": \"texto\", \"conteudo\": \"O while é usado quando não sabemos exatamente quantas vezes um bloco de código deve ser repetido.\"}, {\"tipo\": \"texto\", \"conteudo\": \"contador = 1\\n\\nwhile contador <= 5:\\n    print(f\\\"Repetição {contador}\\\")\\n    contador += 1\\n\\nO loop vai imprimir os números de 1 a 5.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Atenção: Tenha cuidado com loops infinitos! Se a condição nunca for falsa, o loop rodará para sempre!\"}, {\"tipo\": \"texto\", \"conteudo\": \"while True:\\n    print(\\\"Isso nunca para!\\\")\\n\\nPara evitar isso, sempre tenha uma condição que possa ser falsa em algum momento.\"}]', 'teoria', 6, 1, '2025-08-26 23:56:52'),
(36, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Executar código apenas uma vez.\", \"Repetir código enquanto uma condição for verdadeira.\", \"Comparar valores numéricos.\"], \"pergunta\": \"Qual é a principal função do loop while?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"Se a condição do while nunca for falsa, o código pode entrar em um loop infinito.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"Complete o código para que o while pare quando x for maior que 3.\\nx = 0\\nwhile __________:\\n    print(x)\\n    x += 1\", \"resposta_correta\": \"x <= 3\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"1 2 3\", \"1 2 3 4\", \"1 1 1 1\"], \"pergunta\": \"num = 1\\nwhile num < 4:\\n    print(num)\\n    num += 1\", \"resposta_correta\": 0}, {\"dica\": \"Use while com uma condição que verifique se o número é menor ou igual a 10, e dentro do loop peça o número novamente.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um programa que peça um número ao usuário e continue pedindo até que ele digite um número maior que 10.\"}]', 'exercicio', 6, 2, '2025-08-26 23:56:52'),
(37, 'Usando break e continue', '[{\"tipo\": \"texto\", \"conteudo\": \"Vamos agora aprender break e continue!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Essas duas palavras servem para “controlar o fluxo” dentro do while.\"}, {\"tipo\": \"texto\", \"conteudo\": \"O que é o break? O break interrompe o loop do while imediatamente, independente da condição ser verdadeira ou falsa.\"}, {\"tipo\": \"texto\", \"conteudo\": \"while True:\\n    resposta = input(\\\"Digite \'sair\' para parar: \\\")\\n    if resposta == \\\"sair\\\":\\n        break\\n\\nO código só para quando o usuário digita “sair”.\"}, {\"tipo\": \"texto\", \"conteudo\": \"O que é o continue? O continue pula para a próxima repetição do loop.\"}, {\"tipo\": \"texto\", \"conteudo\": \"numero = 0\\nwhile numero < 5:\\n    numero += 1\\n    if numero == 3:\\n        continue\\n    print(numero)\\n\\nEsse código imprime 1, 2, 4 e 5, mas pula o 3.\"}]', 'teoria', 6, 3, '2025-08-26 23:56:52'),
(38, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Interrompe o loop imediatamente.\", \"Faz o loop repetir para sempre.\", \"Pula a próxima repetição do loop.\"], \"pergunta\": \"O que o break faz em um loop?\", \"resposta_correta\": 0}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O continue faz o loop ignorar o restante do código e começar a próxima repetição.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"Complete o código para que ele pare quando x for igual a 3.\\nx = 0\\nwhile x < 5:\\n    x += 1\\n    if x == 3:\\n        __________\", \"resposta_correta\": \"break\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"1 2 3 4\", \"1 3 4\", \"2 3 4\"], \"pergunta\": \"x = 0\\nwhile x < 4:\\n    x += 1\\n    if x == 2:\\n        continue\\n    print(x)\", \"resposta_correta\": 1}, {\"dica\": \"Use while True com break quando o número for 0, e acumule a soma em uma variável.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um programa que peça números ao usuário e some todos eles. O programa deve parar quando o usuário digitar 0.\"}]', 'exercicio', 6, 4, '2025-08-26 23:56:52'),
(39, 'Desafio', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é hora do desafio! Resolva os exercícios no seu computador.\"}, {\"dica\": \"Use uma variável contador que começa em 1 e incrementa até 10.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 1: Crie um programa que exiba os números de 1 a 10 usando um loop while.\"}, {\"dica\": \"Comece com o número digitado e decremente até chegar a 0.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 2: Peça ao usuário para digitar um número e exiba a contagem regressiva desse número até 0 usando while.\"}, {\"dica\": \"Use while True com break quando o número for 0.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 3: Crie um código que peça ao usuário para digitar números até que ele digite o número 0. Quando isso acontecer, o programa deve parar.\"}, {\"dica\": \"Use uma variável para acumular a soma e outra para contar de 1 até o número digitado.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 4: Peça ao usuário para digitar um número e exiba a soma de todos os números de 1 até esse número usando while.\"}, {\"dica\": \"Defina uma senha fixa (ex: \'1234\') e use while para pedir até acertar.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 5: Crie um código que peça a senha ao usuário e continue pedindo até que ele digite a senha correta.\"}]', 'exercicio', 6, 5, '2025-08-26 23:56:52'),
(40, 'Introdução ao For', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender sobre o loop for! Ele é usado para percorrer elementos de uma sequência, como listas e strings.\"}, {\"tipo\": \"texto\", \"conteudo\": \"O que é o for? O for repete um bloco de código para cada item de uma sequência.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Exemplo básico de for:\\nfor i in range(5):\\n    print(f\\\"Repetição {i}\\\")\\n\\nEsse código imprime os números de 0 a 4.\"}, {\"tipo\": \"texto\", \"conteudo\": \"O for também funciona com listas:\\nfrutas = [\\\"maçã\\\", \\\"banana\\\", \\\"uva\\\"]\\nfor fruta in frutas:\\n    print(fruta)\\n\\nCada item da lista é acessado automaticamente pelo for.\"}]', 'teoria', 7, 1, '2025-08-26 23:57:45'),
(41, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Repete um bloco de código um número fixo de vezes.\", \"Executa código apenas uma vez.\", \"Interrompe a execução do programa.\"], \"pergunta\": \"O que o for faz em Python?\", \"resposta_correta\": 0}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O for pode ser usado para percorrer listas e strings.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"Complete o código para percorrer a lista de números e imprimir cada um.\\nnumeros = [1, 2, 3, 4]\\nfor num in __________:\\n    print(num)\", \"resposta_correta\": \"numeros\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Python\", \"P y t h o n\", \"Erro\"], \"pergunta\": \"for letra in \\\"Python\\\":\\n    print(letra)\", \"resposta_correta\": 1}, {\"dica\": \"Use for com if e o operador % para verificar se o número é par (num % 2 == 0).\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um programa que percorra uma lista de números e exiba apenas os pares.\"}]', 'exercicio', 7, 2, '2025-08-26 23:57:45'),
(42, 'Usando Range e Enumerate', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender sobre range() e enumerate(), que ajudam a trabalhar com for.\"}, {\"tipo\": \"texto\", \"conteudo\": \"O que é range()? A função range() gera uma sequência de números automaticamente.\\nfor i in range(1, 6):\\n    print(i)\\n\\nEsse código imprime os números de 1 a 5.\"}, {\"tipo\": \"texto\", \"conteudo\": \"O que é enumerate()?\\nO enumerate() retorna o índice e o valor de uma lista.\\nnomes = [\\\"Ana\\\", \\\"Bruno\\\", \\\"Carlos\\\"]\\nfor indice, nome in enumerate(nomes):\\n    print(indice, nome)\\n\\nEle exibe a posição e o valor de cada item.\"}]', 'teoria', 7, 3, '2025-08-26 23:57:45'),
(43, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Cria uma lista com os números de 1 a 5.\", \"Gera os números de 0 a 4.\", \"Não faz nada.\"], \"pergunta\": \"O que range(5) faz?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O enumerate() pode ser usado para acessar o índice e o valor ao mesmo tempo.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"Complete o código para imprimir os índices e valores da lista.\\nnomes = [\\\"Alice\\\", \\\"Bob\\\", \\\"Carol\\\"]\\nfor __________ in enumerate(nomes):\\n    print(i, nome)\", \"resposta_correta\": \"i, nome\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"0 1 2\", \"1 2 3\", \"0 1 2 3\"], \"pergunta\": \"for i in range(3):\\n    print(i)\", \"resposta_correta\": 0}, {\"dica\": \"Use range(3, 21, 3) para gerar múltiplos de 3 de 3 a 20, ou verifique com % 3 == 0.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um programa que use range() para exibir os múltiplos de 3 de 1 a 20.\"}]', 'exercicio', 7, 4, '2025-08-26 23:57:45'),
(44, 'Desafio', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é hora do desafio! Resolva os exercícios no seu computador.\"}, {\"dica\": \"Use for i in range(1, 21): para gerar números de 1 a 20.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 1: Crie um código que exiba os números de 1 a 20 usando um loop for.\"}, {\"dica\": \"Use for i in range(1, 11): e multiplique pelo número digitado pelo usuário.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 2: Peça ao usuário um número e exiba a tabuada desse número de 1 a 10 usando for.\"}, {\"dica\": \"Use range(2, 51, 2) para gerar apenas números pares, ou verifique com if num % 2 == 0.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 3: Crie um código que exiba todos os números pares de 1 a 50 usando for.\"}, {\"dica\": \"Use for letra in palavra: para percorrer cada caractere da string.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 4: Peça ao usuário para digitar uma palavra e exiba cada letra da palavra separadamente usando for.\"}, {\"dica\": \"Use for _ in range(5): para pedir 5 números e acumule a soma em uma variável.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 5: Crie um código que peça ao usuário para digitar 5 números e, no final, exiba a soma de todos eles.\"}]', 'exercicio', 7, 5, '2025-08-26 23:57:45'),
(45, 'Introdução às Arrays', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender sobre arrays!\"}, {\"tipo\": \"texto\", \"conteudo\": \"Elas são usadas para armazenar vários valores em uma única variável.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Também chamadas de listas, os arrays permitem armazenar vários valores organizados em uma sequência.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Criando uma lista:\\nfrutas = [\\\"maçã\\\", \\\"banana\\\", \\\"uva\\\"]\\nprint(frutas)\\n\\nEsse código cria uma lista e exibe os valores.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Acessando elementos da lista: Cada item tem um índice, começando do 0. Ou seja, para acessar o primeiro item, nós usamos o 0, para acessar o segundo item, nós usamos o item 1 e assim por diante.\\nprint(frutas[0])        # \\\"maçã\\\"\\n\\nIsso exibe o primeiro item da lista.\"}]', 'teoria', 8, 1, '2025-08-26 23:58:31'),
(46, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"numeros[2]\", \"numeros[3]\", \"numeros[1]\"], \"pergunta\": \"Como acessar o terceiro item da lista numeros = [10, 20, 30, 40]?\", \"resposta_correta\": 0}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"Em Python, os índices das listas começam no número 1.\", \"resposta_correta\": false}, {\"tipo\": \"complete\", \"pergunta\": \"Complete o código para exibir \\\"banana\\\".\\nfrutas = [\\\"maçã\\\", \\\"banana\\\", \\\"uva\\\"]\\nprint(__________)\", \"resposta_correta\": \"frutas[1]\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"5\", \"10\", \"15\"], \"pergunta\": \"numeros = [5, 10, 15]\\nprint(numeros[1])\", \"resposta_correta\": 1}, {\"dica\": \"Lembre-se que o segundo item tem índice 1 na lista: amigos = [\\\"amigo1\\\", \\\"amigo2\\\", \\\"amigo3\\\"]\", \"tipo\": \"desafio\", \"pergunta\": \"Crie uma lista com os nomes de 3 amigos e exiba o nome do segundo amigo.\"}]', 'exercicio', 8, 2, '2025-08-26 23:58:31'),
(47, 'Modificando Listas', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender como modificar listas! Podemos alterar, adicionar e remover itens.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Modificando um item da lista: Podemos alterar um item acessando seu índice.\\nfrutas = [\\\"maçã\\\", \\\"banana\\\", \\\"uva\\\"]\\nfrutas[1] = \\\"laranja\\\"\\nprint(frutas)\\n\\nIsso substitui “banana” por “laranja”.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Adicionando itens com append(): O append() adiciona um item ao final da lista.\\nfrutas.append(\\\"manga\\\")\\nprint(frutas)\"}, {\"tipo\": \"texto\", \"conteudo\": \"Removendo itens com remove(): O remove() apaga um item específico da lista.\\nfrutas.remove(\\\"uva\\\")\\nprint(frutas)\"}]', 'teoria', 8, 3, '2025-08-26 23:58:31'),
(48, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"insert()\", \"append()\", \"pop()\"], \"pergunta\": \"Qual método adiciona um item ao final da lista?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"O remove() pode excluir um item da lista pelo seu valor.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"Complete o código para adicionar \\\"pera\\\" à lista.\\nfrutas = [\\\"maçã\\\", \\\"banana\\\"]\\nfrutas.__________(\\\"pera\\\")\", \"resposta_correta\": \"append\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"[1, 2, 3]\", \"[1, 3]\", \"[2, 3]\"], \"pergunta\": \"numeros = [1, 2, 3]\\nnumeros.remove(2)\\nprint(numeros)\", \"resposta_correta\": 1}, {\"dica\": \"Use numeros = [1, 2, 3, 4, 5] e depois numeros.remove(3)\", \"tipo\": \"desafio\", \"pergunta\": \"Crie uma lista com os números de 1 a 5 e remova o número 3.\"}]', 'exercicio', 8, 4, '2025-08-26 23:58:31');
INSERT INTO `licoes` (`id`, `titulo`, `conteudo`, `tipo`, `modulo`, `ordem`, `created_at`) VALUES
(49, 'Desafio', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é hora do desafio! Resolva os exercícios no seu computador.\"}, {\"dica\": \"Use numeros = [1, 2, 3, 4, 5] e for num in numeros: print(num)\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 1: Crie uma lista com 5 números e exiba cada um deles na tela usando um loop for.\"}, {\"dica\": \"Use um loop for para pedir 3 nomes com input() e append() para adicionar à lista.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 2: Peça ao usuário para digitar 3 nomes e armazene-os em uma lista. Depois, exiba todos os nomes digitados.\"}, {\"dica\": \"Use while True com break quando o número for 0, e append() para adicionar à lista.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 3: Crie um código que peça ao usuário para digitar números até que ele digite 0. Armazene os números em uma lista e depois exiba todos eles.\"}, {\"dica\": \"Use for num in numeros: e if num % 2 == 0: para filtrar os pares.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 4: Crie uma lista com 10 números e exiba apenas os números pares contidos nela.\"}, {\"dica\": \"Use max(numeros) e min(numeros) para encontrar o maior e menor valor.\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 5: Peça ao usuário para digitar 5 números e armazene-os em uma lista. Depois, exiba o maior e o menor número da lista.\"}]', 'exercicio', 8, 5, '2025-08-26 23:58:31'),
(50, 'Introdução às Bibliotecas', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos aprender sobre bibliotecas! Elas contêm códigos prontos que facilitam a programação.\"}, {\"tipo\": \"texto\", \"conteudo\": \"O que são bibliotecas? Bibliotecas são conjuntos de funções e módulos prontos para uso.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Importando uma biblioteca:\\nimport math\\n\\nIsso importa a biblioteca math, que tem funções matemáticas.\"}, {\"tipo\": \"texto\", \"conteudo\": \"Usando funções de uma biblioteca:\\nimport math\\nresultado = math.sqrt(25)\\nprint(resultado)  # 5.0\\nresultado2 = math.pow(3, 2)\\nprint(resultado2) #9\\n\\nA função sqrt() calcula a raiz quadrada e a função pow() calcula um número elevado ao outro.\"}]', 'teoria', 9, 1, '2025-08-26 23:58:59'),
(51, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Um programa completo.\", \"Um conjunto de códigos prontos para uso.\", \"Um erro no código.\"], \"pergunta\": \"O que é uma biblioteca em Python?\", \"resposta_correta\": 1}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"Para usar uma biblioteca, é necessário importá-la primeiro.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"Complete o código para importar a biblioteca random.\\n________ random\", \"resposta_correta\": \"import\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"8\", \"6\", \"2³\"], \"pergunta\": \"import math\\nprint(math.pow(2, 3))\", \"resposta_correta\": 0}, {\"dica\": \"Use import math, input() para receber o número e math.sqrt() para calcular a raiz quadrada.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um código que utilize a biblioteca math para calcular a raiz quadrada de um número digitado pelo usuário.\"}]', 'exercicio', 9, 2, '2025-08-26 23:58:59'),
(52, 'Bibliotecas Úteis', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos conhecer algumas bibliotecas úteis do Python!\"}, {\"tipo\": \"texto\", \"conteudo\": \"random – Trabalhando com números aleatórios:\\nimport random\\nnumero = random.randint(1, 10)\\nprint(numero)\\n\\nIsso gera um número aleatório entre 1 e 10.\"}, {\"tipo\": \"texto\", \"conteudo\": \"datetime – Trabalhando com datas:\\nimport datetime\\nhoje = datetime.date.today()\\nprint(hoje)\\n\\nIsso exibe a data atual.\"}, {\"tipo\": \"texto\", \"conteudo\": \"os – Interagindo com o sistema operacional:\\nimport os\\nprint(os.name)  # Mostra o nome do sistema\"}]', 'teoria', 9, 3, '2025-08-26 23:58:59'),
(53, 'Exercícios', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora vamos testar a sua lógica!\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"Trabalha com números aleatórios.\", \"Exibe a data atual.\", \"Gerencia arquivos do sistema.\"], \"pergunta\": \"O que a biblioteca random faz?\", \"resposta_correta\": 0}, {\"tipo\": \"verdadeiro_falso\", \"pergunta\": \"A biblioteca datetime pode ser usada para obter a data atual.\", \"resposta_correta\": true}, {\"tipo\": \"complete\", \"pergunta\": \"Complete o código para gerar um número aleatório de 1 a 100.\\nimport random\\nnumero = random.________(1, 100)\\nprint(numero)\", \"resposta_correta\": \"randint\"}, {\"tipo\": \"multipla_escolha\", \"opcoes\": [\"A data atual.\", \"Um número aleatório.\", \"Um erro.\"], \"pergunta\": \"import datetime\\nprint(datetime.date.today())\", \"resposta_correta\": 0}, {\"dica\": \"Use datetime.date.today().year para obter apenas o ano atual.\", \"tipo\": \"desafio\", \"pergunta\": \"Crie um código que utilize a biblioteca datetime para exibir o ano atual.\"}]', 'exercicio', 9, 4, '2025-08-26 23:58:59'),
(54, 'Desafio', '[{\"tipo\": \"texto\", \"conteudo\": \"Agora é hora do desafio! Resolva os exercícios no seu computador.\"}, {\"dica\": \"Use import math, input() e math.sqrt()\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 1: Utilize a biblioteca math para calcular e exibir a raiz quadrada de um número digitado pelo usuário.\"}, {\"dica\": \"Use import random e random.randint(1, 100)\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 2: Use a biblioteca random para gerar e exibir um número aleatório entre 1 e 100.\"}, {\"dica\": \"Use import math e math.factorial()\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 3: Peça ao usuário para digitar um número e utilize a biblioteca math para calcular e exibir o fatorial desse número.\"}, {\"dica\": \"Use import datetime e datetime.datetime.now()\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 4: Use a biblioteca datetime para exibir a data e a hora atuais.\"}, {\"dica\": \"Use import random e random.choice()\", \"tipo\": \"desafio\", \"pergunta\": \"Desafio 5: Crie um código que sorteie um nome aleatório de uma lista de 5 nomes usando a biblioteca random.\"}]', 'exercicio', 9, 5, '2025-08-26 23:58:59');

-- --------------------------------------------------------

--
-- Estrutura da tabela `modulos`
--

CREATE TABLE `modulos` (
  `id` int NOT NULL,
  `titulo` varchar(80) COLLATE utf8mb4_general_ci NOT NULL,
  `descricao` varchar(200) COLLATE utf8mb4_general_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `modulos`
--

INSERT INTO `modulos` (`id`, `titulo`, `descricao`) VALUES
(1, 'Algoritmos', 'Introdução ao raciocínio lógico por trás da programação. Você aprende a criar sequências de passos bem definidos para resolver problemas.'),
(2, 'Tipos de dados', 'Explicação sobre os diferentes tipos de informações que o Python pode manipular, como números inteiros, decimais, textos e valores lógicos.'),
(3, 'Print e input', 'Como mostrar mensagens na tela com o print() e como receber informações do usuário com o input().'),
(4, 'Operadores', 'Estudo dos operadores aritméticos, relacionais e lógicos em Python, essenciais para realizar cálculos, comparações e tomadas de decisão.'),
(5, 'Estruturas de seleção', 'Como criar condições nos programas: executar certos blocos de código apenas quando critérios forem atendidos, usando if/else e match case.'),
(6, 'While', 'Introdução ao laço de repetição que executa um bloco de código enquanto uma condição for verdadeira.'),
(7, 'For', 'Exploração do laço de repetição usado para percorrer sequências, listas e intervalos de valores de forma prática.'),
(8, 'Arrays', 'Trabalhando com coleções de dados em Python, organizando e manipulando várias informações dentro de uma única estrutura chamada lista.'),
(9, 'Bibliotecas do Python', 'Uso de módulos prontos que expandem as funcionalidades da linguagem, como matemática, tempo, manipulação de arquivos e muito mais.');

-- --------------------------------------------------------

--
-- Estrutura da tabela `progresso`
--

CREATE TABLE `progresso` (
  `id` int NOT NULL,
  `usuario` int NOT NULL,
  `licao` int NOT NULL,
  `data` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Estrutura da tabela `status`
--

CREATE TABLE `status` (
  `id` int NOT NULL,
  `usuario` int NOT NULL,
  `vidas` int NOT NULL DEFAULT '5',
  `ofensiva` int NOT NULL DEFAULT '0',
  `xp` int NOT NULL DEFAULT '0',
  `modulos` int NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `status`
--

INSERT INTO `status` (`id`, `usuario`, `vidas`, `ofensiva`, `xp`, `modulos`) VALUES
(1, 1, 5, 0, 0, 0);

-- --------------------------------------------------------

--
-- Estrutura da tabela `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int NOT NULL,
  `username` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `nome` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `senha` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `foto` varchar(100) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'buncodefault',
  `cor` varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'F2F2F2',
  `link_github` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `link_instagram` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `link_linkedin` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `usuarios`
--

INSERT INTO `usuarios` (`id`, `username`, `nome`, `email`, `senha`, `foto`, `cor`, `link_github`, `link_instagram`, `link_linkedin`, `created_at`) VALUES
(1, 'administrador', 'Administrador', 'administrador@email.com', '7580adf5151c6b79c90597aeab91838f', 'buncoduolingo', 'a4e451', '', '', '', '2025-08-27 18:11:39');

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `licoes`
--
ALTER TABLE `licoes`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_licoes_modulos` (`modulo`);

--
-- Índices para tabela `modulos`
--
ALTER TABLE `modulos`
  ADD PRIMARY KEY (`id`);

--
-- Índices para tabela `progresso`
--
ALTER TABLE `progresso`
  ADD PRIMARY KEY (`id`),
  ADD KEY `licao` (`licao`),
  ADD KEY `progresso_ibfk_1` (`usuario`);

--
-- Índices para tabela `status`
--
ALTER TABLE `status`
  ADD PRIMARY KEY (`id`),
  ADD KEY `status_ibfk_1` (`usuario`);

--
-- Índices para tabela `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `licoes`
--
ALTER TABLE `licoes`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=55;

--
-- AUTO_INCREMENT de tabela `modulos`
--
ALTER TABLE `modulos`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT de tabela `progresso`
--
ALTER TABLE `progresso`
  MODIFY `id` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de tabela `status`
--
ALTER TABLE `status`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT de tabela `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- Restrições para despejos de tabelas
--

--
-- Limitadores para a tabela `licoes`
--
ALTER TABLE `licoes`
  ADD CONSTRAINT `fk_licoes_modulos` FOREIGN KEY (`modulo`) REFERENCES `modulos` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Limitadores para a tabela `progresso`
--
ALTER TABLE `progresso`
  ADD CONSTRAINT `progresso_ibfk_1` FOREIGN KEY (`usuario`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `progresso_ibfk_2` FOREIGN KEY (`licao`) REFERENCES `licoes` (`id`);

--
-- Limitadores para a tabela `status`
--
ALTER TABLE `status`
  ADD CONSTRAINT `status_ibfk_1` FOREIGN KEY (`usuario`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
